---
- name: Install | Add APT source
  shell: echo "deb https://repo.scala-sbt.org/scalasbt/debian /" >> /etc/apt/sources.list.d/sbt.list
  sudo: yes

- name: Install | Add APT key
  shell: curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
  sudo: yes

- name: Install | Update APT
  shell: apt-get update
  sudo: yes

- name: Install | Install SBT
  shell: apt-get install sbt
  sudo: yes
